server:
  port: 8000


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:3005
          predicates:
            - Path=/users/**

        - id: COMMENT-SERVICE
          uri: http://localhost:3015
          predicates:
            - Path=/posts/{postId}/comments/**

        - id: POST-SERVICE
          uri: http://localhost:3010
          predicates:
            - Path=/posts/**

        - id: COMMENT-SERVICE
          uri: http://localhost:3015
          predicates:
            - Path=/posts/{postId}/comments/**

        - id: LIKE-SERVICE
          uri: http://localhost:3020
          predicates:
            - Path=/postsOrComments/{postOrCommentId}/**
        - id: LIKE-SERVICE
          uri: http://localhost:3020
          predicates:
            - Path=/auth/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
#    instance:
#      preferIpAddress: false
#





